### ISSUE TITLE
Crash on non-python file in `./library` folder

### ISSUE THREAD

**Issue by dflock** [willthames/ansible-review#26]
If you have any non-python file into your `./library` folder, `ansible-review` will crash:

```console
$ cat ./ansible/library/test.txt
test string
```

```console
$ ansible-review -v ./ansible/library/test.txt

INFO: Reviewing all of Code (./ansible/library/test.txt)
INFO: Code ./ansible/library/test.txt declares standards version 0.1
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/main/__init__.py", line 95, in main
    errors = errors + candidate.review(options, lines)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/__init__.py", line 72, in review
    return utils.review(self, settings, lines)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/utils/__init__.py", line 120, in review
    result = standard.check(candidate, settings)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/code.py", line 9, in code_passes_flake8
    lineno = int(line.split(':')[1])
ValueError: invalid literal for int() with base 10: ''
```

Presumably this just runs `flake8` on the file, assuming it's python, doesn't trap and crashes. It's valid to write Ansible modules in languages other than python; I came across this because I have a custom module that's written as a shell script.

**Comment by dflock** [comment]
Hmmm. This might be because my local install of `flake8` is broken:

```console
$ flake8 
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flake8==2.1.0' distribution was not found and is required by the application
```

Probably shouldn't make ansible review crash, though?

**Comment by dflock** [comment]
OK, I fixed my `flake8` install and now I get this:

```console
$ ansible-review -v ./ansible/library/test.txt 

INFO: Using configuration file: /home/duncan/.config/ansible-review/config.ini
INFO: Reviewing all of Code (./ansible/library/test.txt)
INFO: Code ./ansible/library/test.txt declares standards version 0.1
WARN: Best practice "Python code should pass flake8" not met:
./ansible/library/test.txt:1: ./ansible/library/test.txt:1:9: E999 SyntaxError: invalid syntax
WARN: Best practice "Python code should pass flake8" not met:
./ansible/library/test.txt:1: ./ansible/library/test.txt:1:10: W292 no newline at end of file
INFO: Best practice "Don't use tabs in almost anything that isn't a Makefile" met
```

So, no crash, but it still tries to parse it as python.
