### ISSUE TITLE
Crash on python file in a `task/templates` folder

### ISSUE THREAD

**Issue by dflock** [willthames/ansible-review#27]
We have a task that needs to use the template module to output a python file to the target node. This tasks folder looks like this:

```console
$ tree ./ansible/roles/test_role
./ansible/roles/test_role
├── files
│   └── other.py
├── tasks
│   ├── main.yml
├── templates
│   ├── test.py
```

The `test.py` jinja template looks like this:

```jinja
DEPLOYMENT = dict(
     env='{{ test.env }}'
)
```

`ansible-review` is trying to `flake8` this file and failing, leading to a crash, same as #26:

```console
$ ansible-review -v ./ansible/roles/test/templates/test.py

INFO: Using configuration file: /home/duncan/.config/ansible-review/config.ini
INFO: Reviewing all of Code (./ansible/roles/test/templates/test.py)
INFO: Code ./ansible/roles/test/templates/test.py declares standards version 0.1
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/main/__init__.py", line 95, in main
    errors = errors + candidate.review(options, lines)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/__init__.py", line 72, in review
    return utils.review(self, settings, lines)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/utils/__init__.py", line 120, in review
    result = standard.check(candidate, settings)
  File "/usr/local/lib/python2.7/dist-packages/ansiblereview/code.py", line 9, in code_passes_flake8
    lineno = int(line.split(':')[1])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by dflock** [comment]
If I rename the file from `test.py` to `test.py.j2` this error goes away:

```console
$ ansible-review -v ./ansible/roles/test/templates/test.py.j2

INFO: Using configuration file: /home/duncan/.config/ansible-review/config.ini
INFO: Reviewing all of Template (./ansible/roles/test/templates/test.py.j2)
WARN: Template ./ansible/roles/test/templates/test.py.j2 is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1
INFO: Template ./ansible/roles/test/templates/test.py.j2 declares standards version 0.1
INFO: Best practice "Variable uses should contain whitespace" met
INFO: Best practice "Don't use tabs in almost anything that isn't a Makefile" met
INFO: Best practice "Don't compare to "" - use `when: var` or `when: not var`" met
INFO: Best practice "Don't compare to True or False - use `when: var` or `when: not var`" met
```

**Comment by dflock** [comment]
Busted `flake8` install, same as #26, sorry.
