### ISSUE TITLE
Traceback error on missing double quotes in yaml with Jinja2

### ISSUE THREAD

**Issue by nvtkaszpir** [willthames/ansible-review#33]
Python 2.7.12
pip freeze (fragment):
```text
ansible==2.2.1.0
ansible-lint==3.4.13
ansible-review==0.13.0
```
source yaml:
```yaml
  - name: This code will fail because 'port' does is not wrapped in double quotes
    wait_for:
      host: "{{ somevar }}"
      port: {{ i_have_missing_double_quotes }}
      timeout: "{{ i_am_ok }}"
```

error trace:
```bash
censored/roles/censored/tasks/main.yml:29: Task arguments appear to be in key value rather than YAML format
Traceback (most recent call last):
  File "censored/.venv/bin/ansible-review", line 11, in <module>
    sys.exit(main())
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblereview/main/__init__.py", line 95, in main
    errors = errors + candidate.review(options, lines)
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 72, in review
    return utils.review(self, settings, lines)
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblereview/utils/__init__.py", line 120, in review
    result = standard.check(candidate, settings)
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 219, in ansiblelint
    matches = rules.run(fileinfo, rulename.split(','))
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 66, in matchtasks
    yaml = ansiblelint.utils.parse_yaml_linenumbers(text, file['path'])
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 524, in parse_yaml_linenumbers
    data = loader.get_single_data()
  File "censored/.venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "censored/.venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "censored/.venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "censored/.venv/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 515, in construct_mapping
    mapping = Constructor.construct_mapping(loader, node, deep=deep)
  File "censored/.venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "censored/.venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 132, in construct_mapping
    "found unacceptable key (%s)" % exc, key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 54, column 13:
          port: {{ i_have_missing_double_quotes }}
                ^
found unacceptable key (unhashable type: 'dict')
  in "<unicode string>", line 54, column 14:
          port: {{ i_have_missing_double_quotes }}
                 ^

```

Expected behaviour:
no traceback but meaningful error explanation.

**Comment by willthames** [comment]
ansible-review is not a substitute for ansible --syntax-check

That said, it should handle this exception better, you're quite right.
