### ISSUE TITLE
Unable to Load Variables from Directories within defaults/main

### ISSUE THREAD

**Issue by paulcalabro** [willthames/ansible-review#69]
This is a new feature with Ansible 2.6.
More information regarding it can be found here:

https://github.com/ansible/ansible/pull/36357

Currently, an `IOError` is raised.

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ansiblereview/__main__.py", line 86, in main
    candidate = classify(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 184, in classify
    return RoleVars(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 87, in __init__
    super(RoleFile, self).__init__(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 68, in __init__
    self.version = find_version(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblereview/__init__.py", line 231, in find_version
    with codecs.open(filename, mode='rb', encoding='utf-8') as f:
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 21] Is a directory: './roles/foreman-server/defaults/main'
```

**Comment by willthames** [comment]
Can you provide an example failing playbook please?
