### ISSUE TITLE
ansible-review v0.14.0rc2 produces stacktrace when checking azure_rm.yml inventory plugin

### ISSUE THREAD

**Issue by ansiblejunky** [willthames/ansible-review#87]
The stacktrace happens because ansible-review attempts to access/load the inventory plugin and the plugin needs to `import msrest`, but this module is not inside the pre-commit environment.  Perhaps this is an issue with pre-commit, but I am not exactly sure yet. 

Here is the stacktrace:
```
ansible-review...........................................................Failed
hookid: ansible-review

WARN: Playbook Build.yml does not present standards version. Using latest standards version 0.1
WARN: Best practice "YAML should be correctly indented" not met:
Build.yml:8: lines starting with '- ' should have same or less indentation than previous line (indent_list_items is False)
Traceback (most recent call last):
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/bin/ansible-review", line 10, in <module>
    sys.exit(main())
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/__main__.py", line 102, in main
    errors = errors + candidate.review(options, lines)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/__init__.py", line 76, in review
    return utils.review(self, settings, lines)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/utils/__init__.py", line 121, in review
    result = standard.check(candidate, settings)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/groupvars.py", line 45, in same_variable_defined_in_competing_groups
    inv = _inv or InventoryManager(invfile).inventory
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/inventory.py", line 86, in __init__
    vault_password_files, vault_ids)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansiblereview/inventory.py", line 23, in __init__
    sources=inventory)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/inventory/manager.py", line 162, in __init__
    self.parse_sources(cache=True)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/inventory/manager.py", line 220, in parse_sources
    parse = self.parse_source(source, cache=cache)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/inventory/manager.py", line 254, in parse_source
    parsed_this_one = self.parse_source(fullpath, cache=cache)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/inventory/manager.py", line 266, in parse_source
    for plugin in self._fetch_inventory_plugins():
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/inventory/manager.py", line 199, in _fetch_inventory_plugins
    plugin = inventory_loader.get(name)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/plugins/loader.py", line 530, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/home/user/.cache/pre-commit/repoN7_lSN/py_env-python2.7/lib/python2.7/site-packages/ansible/plugins/inventory/azure_rm.py", line 186, in <module>
    from msrest import ServiceClient, Serializer, Deserializer
ImportError: No module named msrest

Success.
```

**Comment by ansiblejunky** [comment]
I actually figured it out. Seems we need to tell pre-commit to add some of these dependencies to the pre-commit environment.  Do it using this example for handling azure inventory plugin:
```
---
repos:
  - repo: https://github.com/willthames/ansible-review.git
    rev: v0.14.0rc2
    hooks:
      - id: ansible-review
        name: ansible-review
        entry: ansible-review -c .ansible-review
        verbose: false
        # required for ansible-review to handle azure inventory plugin
        additional_dependencies: ['msrest', 'msrestazure']
```
Now the pre-commit works perfectly again.
