### ISSUE TITLE
Stack trace/error upon finding vault string in playbook vars

### ISSUE THREAD

**Issue by rybal06** [willthames/ansible-review#89]
This ansible playbook:
```
- hosts: mytestgroup
  gather_facts: true
  tasks:
  - name: "install ssh key"
    vars:
      SSH_KEY: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          < value omitted >
```
Is producing this stack trace below: 
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ansiblereview/__main__.py", line 99, in main
    errors = errors + candidate.review(options, lines)
  File "/usr/local/lib/python3.7/site-packages/ansiblereview/__init__.py", line 76, in review
    return utils.review(self, settings, lines)
  File "/usr/local/lib/python3.7/site-packages/ansiblereview/utils/__init__.py", line 120, in review
    result = standard.check(candidate, settings)
  File "/usr/local/lib/python3.7/site-packages/ansiblereview/examples/standards.py", line 37, in files_should_have_actual_content
    content = yaml.safe_load(f.read())
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!vault'
  in "<unicode string>", line 6, column 16:
          SSH_KEY: !vault |
                   ^
```

**Comment by rybal06** [comment]
I missed that there is an open PR for this already, closing this as a duplicate
